name: Integration tests

on:
  pull_request:
  push:
    branches:
    - 'git' #todo change!

env:
  GOARCH: amd64
  CGO_ENABLED: 0
  SETUP_GO_VERSION: '1.19.*'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    #container:
      #image: docker:dind
     # volumes:
     # - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}

      - name: integration-test
        run: go test ./integrationtests/...
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
